config/routes.rb
Bills::Application.routes.draw do
  root :to => 'home#dashboard'
  resources :tenants, only: [:new, :create, :edit, :update] do
    collection do
      get 'history' => 'tenants#history'
    end
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :gender

  as_enum :gender_cd, column_name: :gender
end

app/models/tenant.rb
class Tenant < Person

  attr_accessible :name, :date_in, :date_out, :color, :email

  def male?
    gender == 0
  end

	def still_in?
    date_out.blank? || date_out > DateTime.now
	end

	def was_there_this_day?(day)
  	if day < date_in.to_date
  		return false
  	else
  		if date_out.nil?
  			return true
  		else
  			return day <= date_out.to_date
	  	end
	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def dashboard
		@dashboard_presenter = DashboardPresenter.new(view_context)
	end

end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def edit
    @tenant = Tenant.find(params[:id])
  end

  def update
    @tenant = Tenant.find(params[:id])
    if @tenant.update_attributes(params[:tenant])
      redirect_to '/'
    else
      render :edit
    end
  end

  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(params[:tenant])
    if @tenant.save
      redirect_to '/'
    else
      render :new
    end
  end

  def history
    @tenants = Tenant.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/_bill.html.erb
<% color = bill[1] %>
<% bill = bill[0] %>

<li class="<%= bill %>" id="<%= bill %>_li" data-bill="<%= bill %>">
	<div style="height: 200px;">
		<div style="margin-top: 40px">
			<span style="margin-left: 40%"><%= t("bills.#{bill.downcase}") %></span>
			<input id="<%= bill %>_start_input" class="<%= bill %> start datepicker" data-type="<%= bill %>" data-selected_date="" type="text" placeholder="Data de início">
			<input id="<%= bill %>_end_input" class="<%= bill %> end datepicker" data-type="<%= bill %>"  data-selected_date="" type="text" placeholder="Data de fim">
			<input class="price_input" data-type="<%= bill %>" type="text" placeholder="Valor da factura" onKeyUp="$.bills.billPriceChanged(this);">
			<span class="days" style="margin-left: 10px">--- dias</span>
			<span class="price_per_day_span <%= bill %>" data-value="" style="float: right; margin-right: 10px">--- €/dia</span>
		</div>
	</div>
</li>

app/views/bills/_list.html.erb
<ul class="bills_list">
	<% @dashboard_presenter.possible_bills.each do |bill| %>
		<%= render 'bills/bill', bill: bill %>
	<% end %>
</ul>
ul><script>
	$(function() {
		$.bills.bills_array = <%= raw @dashboard_presenter.possible_bills_names %>;
		$.bills.loadAllPickers();
	})
</script>

app/views/home/_bills_info.html.erb
<ul class="bills_main_info">
	<% @dashboard_presenter.possible_bills.each do |bill| %>
		<%= render 'bill', bill: bill %>
	<% end %>
</ul>

<script>
	$(function() {
		$.bills.bills_array = <%= raw @dashboard_presenter.possible_bills_names %>;
		$.bills.loadAllPickers();
	});
</script>

app/views/home/_bills_prices_and_dates.html.erb
Tabela de contas e datas das contas

app/views/home/_chart.html.erb
<div class="bills_people_division"></div>
<div id="chart"></div>

<script>
	$(function() {
		var series = [];
		var tenantsCount = <%= @dashboard_presenter.tenants.count %>
		<% @dashboard_presenter.tenants.reverse.each_with_index do |tenant, i| %>
			var tenant_series = {
				name: '<%= tenant.name %>',
				color: '<%= tenant.color %>',
				tenant_id: <%= tenant.id %>,
				data: [[<%= tenant.date_in_in_millis %>, <%= i + 1 + 2 + 0.1 %>, <%= i + 1 + 3 -0.1 %>],[<%= tenant.date_out_in_millis %>, <%= i + 1 + 2 + 0.1 %>, <%= i + 1 + 3 - 0.1 %>]]
			}
			series.push(tenant_series);
		<% end %>


		var d1 = new Date(2014, 3, 1);

		var powerSeries = {
				name: 'power',
				color: "#e2b025",
				data: [[d1.getTime(), 0, 1],[d1.getTime(), 0, 1]]
		}

		var gasSeries = {
				name: 'gas',
				color: "#CC0000",
				data: [[d1.getTime(), 1, 2],[d1.getTime(), 1, 2]]
		}

		var waterSeries = {
				name: 'water',
				color: "#03baf6",
				data: [[d1.getTime(), 2, 3],[d1.getTime(), 2, 3]]
		}

		series.push(powerSeries);
		series.push(gasSeries);
		series.push(waterSeries);

		seriesOptions = {
			series: series,
		}

		$.highcharts.initChart(seriesOptions);
	})
</script>

app/views/home/_people_info.html.erb
<ul class="people_list">
<% @dashboard_presenter.tenants.each do |tenant| %>
	<li style="background: <%= tenant.color %>" class="person" data-tenant_in="<%= tenant.entered_on %>" data-tenant_out="<%= tenant.really_exited_on %>" data-tenant_id="<%= tenant.id %>" data-name="<%= tenant.name %>">
		<div style="display: inline-block">
			<%#= image_tag "#{actors.sample}.jpg", id: "tentant_#{tenant.id}_image", style: 'width: 75px; height: 100px' %>
		</div>
			<div><%= tenant.name %></div>
			<div>numicago@gmail.com</div>
			<div>Entrou Saíu</div>
			<div><%= tenant.entered_on %> <%= tenant.really_exited_on %></div>
			<div>Total a pagar: </div>
		</div>
		<div>
			<%#= image_tag "#{actors.sample}.jpg", id: "tentant_#{tenant.id}_image" %>
			<%= image_tag "https://dl.dropboxusercontent.com/u/2001692/actor/#{actors.sample}.jpg", id: "tentant_#{tenant.id}_image" %>
		</div>
	</li>
<% end %>

<% if @dashboard_presenter.tenants.count < house_max %>
	<li>
		<div onclick="newPersonInput(this)">+</div>
		<script>
			function newPersonInput(element) {
				var $element = $(element);
				$element.parent().html("<div>Foto Nome email entrou saiu</div>");
			}
		</script>
	</li>
<% end %>
</ul>

app/views/home/_people_vs_bills_table.html.erb
<table>
	<tr>
		<th></th>
		<% @dashboard_presenter.possible_bills_names.each do |bill| %>
			<th><%= t("bills.#{bill}") %></th>
		<% end %>
		<th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
	</tr>
	<% @dashboard_presenter.tenants.each do |tenant| %>
	<tr>
		<td style="background-color: <%= tenant.color %>"><%= tenant.name %></td>
		<% @dashboard_presenter.possible_bills_names.each do |bill| %>
			<td class='<%= "#{bill} tenant_#{tenant.id}" %>'></td>
		<% end %>
		<td class='<%= "total_tenant_#{tenant.id}" %>'></td>
	</tr>
	<% end %>
	<tr>
			<td class="total">&nbsp;</td>
		<% @dashboard_presenter.possible_bills_names.each do |bill| %>
			<td class="<%= "total_#{bill}" %>"></td>
		<% end %>
		<td class="total_bills"></td>
	</tr>
</table>

app/views/home/dashboard.html.erb
 <div class="section section_1">
 	<div class="arrow"></div>
 	<div class="top_container">Gestão de contas para senhorios.</div>
 </div>

 <div class="section section_2">
 	<div class="arrow"></div>
 		<%= render 'tenants/list' %>
 </div>

 <div class="section section_3">
 	<div class="arrow"></div>
	<%= render 'bills/list' %>
 </div>

	<div class="section section_4">
		<div style="display: inline-block">
			<%= render 'chart' %>
		</div>
		<div style="display: inline-block; width: 48%; height: 100%">
			<%= render 'people_vs_bills_table' %>
		</div>
	</div>

 <div class="section footer">
 	<div class="arrow"></div>
 	<div>Desenvolvido por: Nuno Gonçalves</div>
 	<div class="email">numicago@gmail.com</div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bills</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,700' rel='stylesheet' type='text/css' />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tenants/_form.html.erb
<%= simple_form_for @tenant do |f| %>
  <%= f.input :name %>
  <%= f.input :date_in, as: :string, input_html: { class: 'datepicker', value: f.object.date_in, }  %>
  <%= f.input :date_out, as: :string, input_html: { class: 'datepicker', value: f.object.date_out, } %>
  <%= f.input :color, as: :minicolors %>
  <%= f.input :email %>

  <%= f.input :gender, collection: [:male, :female], input_html: { value: f.object.gender } %>
  <%= f.submit %>
<% end %>

<script>
  $(function() {
    $('.datepicker').pickadate({
        max: new Date(),
        formatSubmit: 'yyyy-mm-dd',
        onSet: function(event) {
          $.bills.afterDateSelected(this);
        }
      });
  })
</script>

app/views/tenants/_list.html.erb
<%= link_to "Histórico de Inquilinos", history_tenants_path %>
<div class="container">
  <ul class="ch-grid">
      <% @dashboard_presenter.tenants.each_with_index do |tenant, i| %>
      <li class="person" data-tenant_id="<%= tenant.id %>" data-name="<%= tenant.name %>" data-tenant_in="<%= tenant.entered_on %>" data-tenant_out="<%= tenant.really_exited_on %>">
        <div class="ch-item">
          <div class="ch-info">
            <h3><%= tenant.name %></h3>
            <p><%= tenant.email %></p>
            <p>Entrou a <%= tenant.entered_on %></p>
            <p><%= tenant.exited_on %></p>
            <p><%= link_to "Editar", edit_tenant_path(tenant.id), class: "edit" %></p>
          </div>
          <div class="ch-thumb ch-img-1" style="background-image: url(<%= tenant.image %>); background-repeat: no-repeat; background-size: 220px 220px"
            <p id="total_tenant_<%= tenant.id %>"style="margin-top: 162px; font-size: 40px; opacity: 0.4"></p>
          </div>
        </div>
      </li>
    <% end %>
    <li>
      <div class="ch-item">
        <div class="ch-info">
          <h3><%= link_to "Adicionar novo inquilino", new_tenant_path %></h3>
        </div>
        <div class="ch-thumb ch-img-1" style="background-image: url(http://b.dryicons.com/images/icon_sets/colorful_stickers_icons_set/png/256x256/add.png); background-size: 220px 220px; background-repeat: no-repeat"</div>
    </li>
  </ul>
</div>

app/views/tenants/edit.html.erb
<%= render 'form' %>

app/views/tenants/history.html.erb
<ul>
  <% @tenants.each do |tenant| %>
    <li><%= tenant.name %></li>
  <% end %>
</ul>

app/views/tenants/new.html.erb
<%= render 'form' %>